---
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: Test321!
    ports:
      - "5672:5672"
      - "15672:15672"

  localstack:
    image: localstack/localstack:1.4.0
    volumes:
      - "localstackdata:/tmp/localstack"
      - "./localstack/localstack-init.sh:/docker-entrypoint-initaws.d/localstack-init.sh"
    ports:
      - '4563-4599:4563-4599'
    environment:
      SERVICES: sqs
      PERSISTENCE: /tmp/localstack/data # needed for persistance
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    healthcheck:
      test: "awslocal sqs list-queues"
      interval: 10s
volumes:
  localstackdata:
